### ISSUE TITLE
Zoom In cursor missing animations

### ISSUE THREAD

**Issue by EverSurroundingSound** [supermariofps/hatsune-miku-windows-linux-cursors#13]
She doesn't blink like the zoom out cursor :(

**Comment by EverSurroundingSound** [comment]
Do you at least have the files so I can fix it myself?

**Comment by supermariofps** [comment]
Hi! Sorry for taking so long, tomorrow I'll see how I can fix it because I will need to update the HiDPI support but, I don't have the updated script right now

**Comment by supermariofps** [comment]
Okay, before going to sleep, I took a little look at the file and saw that I could edit the different sizes directly in the editor, so I can edit it manually! I'll be updating the Windows and Linux versions tomorrow! Thank you for pointing this out!

**Comment by supermariofps** [comment]
[Fixed!](https://github.com/supermariofps/hatsune-miku-windows-linux-cursors/releases/tag/1.2.5)

**Comment by EverSurroundingSound** [comment]
Thank you so much. I know it's a minor thing but I'm glad it's fixed now
