### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by 4e554c4c** [supermariofps/hatsune-miku-windows-linux-cursors#4]
It would be nice to have releases for windows and linux separately, so that they can be automatically downloaded and installed

My use case is that I usually automatically download releases for font and icon resources from github and apply them onto my desktop, to make sure that I always have the most recent version.

**Comment by supermariofps** [comment]
okay! I'll start putting the zip files on the releases from now on, I'm a bit new on GitHub so If I do something wrong on the releases please let me know!

**Comment by 4e554c4c** [comment]
This is not entirely how I imagined it. I really appreciate the work though! See #12 for an automated way to do this for linux and windows
