### ISSUE TITLE
Hand 1, Hand 2 empty.

### ISSUE THREAD

**Issue by chapstick404** [supermariofps/hatsune-miku-windows-linux-cursors#6]
The file hand1 is empty and so the symlink for hand2 is also empty. Looks like hand1 should point to hand2.

**Comment by supermariofps** [comment]
Thanks for letting me know! I tried to export the png's to work on a fix for it but I ended up facing a problem with the files coming out with the wrong colors so I'll see what I can do as soon as I get some free time

**Comment by supermariofps** [comment]
Alright, I have spent the entire day trying to figure out what was happening using the scripts provided by @4e554c4c on this [pull request ](https://github.com/supermariofps/hatsune-miku-windows-linux-cursors/pull/5) and, for some reason, the hand1_ and 2 always get corrupted when I try to export them while any other cursor works as intended.

I also tried doing an entirely new cursor file with the same sprites to see if somehow a frame got corrupted but I still get the following output regardless

```
Converting cursor...
##################################################
Conversion successfully done!(8 images were output.)
/mnt/HD1/test
xcursorgen: PNG error while reading ha011_000.png
Converting cursor...
##################################################
Conversion successfully done!(8 images were output.)
/mnt/HD1/test
xcursorgen: PNG error while reading ha012_000.png
```

Not sure why those two in particular always get corrupted but, I'll keep looking for a solution to this.

**Comment by 4e554c4c** [comment]
oops! must have done these two wrong. In the meantime they can be downgraded to the old version
