### ISSUE TITLE
Thank you for making this

### ISSUE THREAD

**Issue by Lxtharia** [supermariofps/hatsune-miku-windows-linux-cursors#8]
I have this theme on all my machines and I'm happy everytime I see it :D

**Comment by toydotgame** [comment]
I downloaded it for a meme (i'm very happy with my windows 7 cursors) and then unironically just kinda really got used to it. like an animated normal cursor is weird at first but now if my cursor is normal and not miku shaped something feels off lmao

**Comment by supermariofps** [comment]
I'm happy to be able to bring something like this to you all! and thanks a lot to everyone who is helping keep it working too! <3
