### ISSUE TITLE
Cursor doesn't display correctly on KDE Plasma 5 (Kubuntu 24.04)

### ISSUE THREAD

**Issue by AdamIskandar-39** [supermariofps/hatsune-miku-windows-linux-cursors#9]
I installed this cursor theme from KDE settings and applied it. But however it will fall back to default theme (Breeze) when I'm on desktop while it will display correctly in all programs. I have added ```Inherits=miku-cursor-linux``` line to index.theme file and still changes nothing unfortunately.

**Comment by AdamIskandar-39** [comment]
I forgot to mention, if I log into Plasma 5.27 Wayland session with this cursor applied, plasmashell would froze for some reason

**Comment by elevavmars** [comment]
try adding "XCURSOR_THEME=miku-cursor-linux" into ~/.profile and then reboot

**Comment by AdamIskandar-39** [comment]
> try adding "XCURSOR_THEME=miku-cursor-linux" into ~/.profile and then reboot

Thanks! Doing this alongside creating index.theme file inside ~/.icons/default fixed this problem.

To anyone who found this issue post from Google, do these steps:
1. Edit .profile file in your home dir using any text editor and add `export "XCURSOR_THEME=miku-cursor-linux"` into that file.
2. Create "default" dir inside ~/.icons
3. In that directory, create index.theme with this content:
`[Icon Theme]`
`Name=Miku Cursor`
`Comment=Miku Cursors for Linux!`
`Inherits=miku-cursor-linux`
4. Logout and login or reboot. The cursor theme should be applied properly after you've done all of the steps above.

**Comment by toydotgame** [comment]
+1ing this for the Google folks. I did this a while ago when installing this cursor theme and I have also done it for others in the past just to work around general KDE jankiness occasionally. A little dotfiles edit and a reboot gets the cursors showing up in 100% of applications rather than just a few.
